### ISSUE TITLE
KeyError: 'generator' same error in Linux and Windows

### ISSUE THREAD

**Issue by playdasegunda** [yuan1615/AdaVocoder#1]
Hi, I'm trying to use AdaVocoder, but I'm getting the same error on both Windows and Ubuntu.

I've already installed the dependencies, but I'm getting the following error when I try to run the inference command:

python inference.py --checkpoint_file "/content/AdaVocoder/AISHELL3_pretrained_models/do_00100000" --model_name adahifi-gan

Windows:

Why do I get this error? and how can I be fixing it?

Error:

```
Initializing Inference Process..
Loading '/content/AdaVocoder/AISHELL3_pretrained_models/do_00100000'
Complete.
Traceback (most recent call last):
  File "inference.py", line 97, in <module>
    main()
  File "inference.py", line 93, in main
    inference(a)
  File "inference.py", line 43, in inference
    generator.load_state_dict(state_dict_g['generator'])
KeyError: 'generator'
```

**Comment by playdasegunda** [comment]
i saw that i needed to add the .pt extension to the do_00100000 and g_00100000 model, but i can only use the "g_00100000" model, i can't use the larger do_00100000 model, when i try to use it, i get the same error still, i haven't found a solution for that yet, if you can help i'd appreciate it.

**Comment by yuan1615** [comment]
> This parameter (--checkpoint_file) should be set to the folder in which the model resides, not the model itself. You can try the following code.

python inference.py --checkpoint_file "/content/AdaVocoder/AISHELL3_pretrained_models" --model_name adahifi-gan

**Comment by yuan1615** [comment]
> Hi, I'm trying to use AdaVocoder, but I'm getting the same error on both Windows and Ubuntu.
> 
> I've already installed the dependencies, but I'm getting the following error when I try to run the inference command:
> 
> python inference.py --checkpoint_file "/content/AdaVocoder/AISHELL3_pretrained_models/do_00100000" --model_name adahifi-gan
> 
> Windows:
> 
> Why do I get this error? and how can I be fixing it?
> 
> Error:
> 
> ```
> Initializing Inference Process..
> Loading '/content/AdaVocoder/AISHELL3_pretrained_models/do_00100000'
> Complete.
> Traceback (most recent call last):
>   File "inference.py", line 97, in <module>
>     main()
>   File "inference.py", line 93, in main
>     inference(a)
>   File "inference.py", line 43, in inference
>     generator.load_state_dict(state_dict_g['generator'])
> KeyError: 'generator'
> ```

@lucasbr15 
This parameter (--checkpoint_file) should be set to the folder in which the model resides, not the model itself. You can try the following code.
python inference.py --checkpoint_file "/content/AdaVocoder/AISHELL3_pretrained_models" --model_name hifi-gan

**Comment by playdasegunda** [comment]
Hi, I tried using the command you suggested, however, I received this error:

```
C:\Users\lucas\Downloads\AdaVocoder>python inference.py --checkpoint_file "C:\Users\lucas\Downloads\AdaVocoder\pretrained_models" --model_name hifi-gan
Initializing Inference Process..
Traceback (most recent call last):
  File "C:\Users\lucas\Downloads\AdaVocoder\inference.py", line 97, in <module>
    main()
  File "C:\Users\lucas\Downloads\AdaVocoder\inference.py", line 93, in main
    inference(a)
  File "C:\Users\lucas\Downloads\AdaVocoder\inference.py", line 42, in inference
    state_dict_g = load_checkpoint(a.checkpoint_file, device)
  File "C:\Users\lucas\Downloads\AdaVocoder\inference.py", line 20, in load_checkpoint
    assert os.path.isfile(filepath)
AssertionError

C:\Users\lucas\Downloads\AdaVocoder>
```

This is the content that is inside the "pretrained_models" folder.
![Screenshot_1](https://user-images.githubusercontent.com/97372669/197487210-c5de05c5-526f-44ea-8cda-13371b78e2db.png)
_I've tried removing the .pt from both files, but the same error still happens_

What could it be? Thank you.

**Comment by yuan1615** [comment]
@lucasbr15 
Sorry, I didn't see your question clearly before. The model marked with g is the generator, d is the discriminator, and only the generator is needed in the inference process (you have already run it successfully). The discriminator is only required during subsequent training.
My previous answer was wrong, the --checkpoint_file parameter needs to point to the model file instead of the folder. The code I tested is as follows:

 python inference.py --checkpoint_file ./cp_hifigan/g_00100000 --model_name hifi-gan

**Comment by jreoka** [comment]
Hello! I am getting the error:

```
Initializing Inference Process..
Loading '/content/AdaVocoder/cp_ada_hifigan/g_00100000'
Complete.
Removing weight norm...
/content/AdaVocoder/meldataset.py:15: WavFileWarning: Chunk (non-data) not understood, skipping it.
  sampling_rate, data = read(full_path)
Traceback (most recent call last):
  File "inference.py", line 97, in <module>
    main()
  File "inference.py", line 93, in main
    inference(a)
  File "inference.py", line 56, in inference
    x = get_mel(wav.unsqueeze(0))
  File "inference.py", line 28, in get_mel
    return mel_spectrogram(x, h.n_fft, h.num_mels, h.sampling_rate, h.hop_size, h.win_size, h.fmin, h.fmax)
  File "/content/AdaVocoder/meldataset.py", line 61, in mel_spectrogram
    y = torch.nn.functional.pad(y.unsqueeze(1), (int((n_fft-hop_size)/2), int((n_fft-hop_size)/2)), mode='reflect')
NotImplementedError: Only 2D, 3D, 4D, 5D padding with non-constant padding are supported for now
```
When attempting to do what you instructed. Is something wrong?
