### ISSUE TITLE
Possible to use pretrained VCTK_ model from Hifi-GAN?

### ISSUE THREAD

**Issue by skol101** [yuan1615/AdaVocoder#4]

**Comment by yuan1615** [comment]
Yes, you can try

**Comment by skol101** [comment]
I don't think, since official Hifigan repo provides only generator https://drive.google.com/drive/folders/1vJlfkwR7Uyheq2U5HrPnfTm-tzwuNuey , whilst to resume here from checkpoint, both generator and discriminator are required.

```
checkpoints directory :  cp_hifigan
Loading 'cp_hifigan/g_00440000'
Complete.
Loading 'cp_hifigan/do_00440000'
Complete.
Loading 'cp_hifigan/do_00440000'

**Comment by yuan1615** [comment]
There are two ways you can try this:
1. You can train a VCTK model that includes generators and discriminators.
2. Use this universal model, which contains generators and discriminators.
https://drive.google.com/drive/folders/1YuOoV3lO2-Hhn1F2HJ2aQ4S0LC1JdKLd

**Comment by skol101** [comment]
Cheers, since my requirements are 24k sampling rate, have to train from the scratch.
